security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        # --- PUBLIC ---
        - { path: ^/api/questions, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/questions/\d+, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/answers/question, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/answers/\d+, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/answers$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/categories, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/categories/\d+, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/tags, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/tags/\d+, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/users$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/users/\d+, roles: PUBLIC_ACCESS, methods: [GET] }

        # --- ROLE_USER ---
        - { path: ^/api/questions, roles: ROLE_USER, methods: [POST, PUT, DELETE] }
        - { path: ^/api/answers, roles: ROLE_USER, methods: [PUT, DELETE] }
        - { path: ^/api/answers/\d+/mark-best, roles: ROLE_USER, methods: [POST] }
        - { path: ^/api/users/\d+, roles: ROLE_USER, methods: [PUT] }

        # --- ROLE_ADMIN ---
        - { path: ^/api/categories, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/tags, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/users/\d+, roles: ROLE_ADMIN, methods: [DELETE] }

        # --- Default: any /api requires auth ---
        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
